# Generated by Django 2.1.1 on 2019-02-08 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='procedure_location',
            name='provider',
        ),
    ]
