# Generated by Django 2.1.1 on 2019-02-07 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190207_0507'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProcedureLocation',
            new_name='Procedure_Location',
        ),
    ]
