# Generated by Django 2.1.1 on 2019-02-08 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190208_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='provider',
            field=models.ManyToManyField(through='api.Procedure_Location', to='api.Provider'),
        ),
        migrations.AddField(
            model_name='procedure_location',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Provider'),
        ),
    ]
