# Generated by Django 2.1.1 on 2019-02-08 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190208_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure_location',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='api.Location'),
        ),
        migrations.AlterField(
            model_name='procedure_location',
            name='procedure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedure', to='api.Procedure'),
        ),
    ]
