# Generated by Django 2.1.1 on 2019-02-10 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190208_0052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Procedure_Location',
            new_name='Specialty',
        ),
    ]
