# Generated by Django 2.1.1 on 2019-02-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_location_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='lat',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='long',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
