# Generated by Django 2.1.1 on 2019-02-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190216_1526'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='long',
            field=models.IntegerField(null=True),
        ),
    ]
