# Generated by Django 2.1.1 on 2019-02-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_loggedIn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_patient',
            field=models.BooleanField(default=False),
        ),
    ]
