# Generated by Django 2.1.1 on 2019-02-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190221_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='CPT_Code',
            field=models.CharField(default='', max_length=10),
        ),
    ]
